# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{object_proxy}
  s.version = "1.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Danger Canty"]
  s.date = %q{2011-04-10}
  s.description = %q{Tiny class that defers nearly all method calls to an object of your choice}
  s.email = %q{rubygems@6brand.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.txt"
  ]
  s.files = [
    "History.txt",
    "LICENSE",
    "Manifest.txt",
    "README.txt",
    "Rakefile",
    "VERSION",
    "init.rb",
    "install.rb",
    "lib/object_proxy.rb",
    "lib/object_proxy_safe_hash.rb",
    "object_proxy.gemspec",
    "rails/init.rb",
    "test/test_object_proxy.rb",
    "test/test_object_proxy_safe_hash.rb"
  ]
  s.homepage = %q{http://github.com/JackDanger/object_proxy}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{An even lighter-weight version of BlankSlate for wrapping Ruby objects}
  s.test_files = [
    "test/test_object_proxy.rb",
    "test/test_object_proxy_safe_hash.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

