# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{object_proxy}
  s.version = "1.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Danger Canty"]
  s.date = %q{2010-07-15}
  s.description = %q{Tiny class that defers nearly all method calls to an object of your choice}
  s.email = %q{rubygems@6brand.com}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/object_proxy.rb",
     "lib/object_proxy_safe_hash.rb",
     "object_proxy.gemspec",
     "rails/init.rb",
     "test/test_object_proxy.rb",
     "test/test_object_proxy_safe_hash.rb"
  ]
  s.homepage = %q{http://github.com/JackDanger/object_proxy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{An even lighter-weight version of BlankSlate for wrapping Ruby objects}
  s.test_files = [
    "test/test_object_proxy.rb",
     "test/test_object_proxy_safe_hash.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

